GNERC_TYPE4 = 13
GNERC_TYPE5 = 14
GNERC_TYPE6 = 15
GNERC_TYPE8 = 16
GNERC_TYPES = [GNERC_TYPE4, GNERC_TYPE5, GNERC_TYPE6, GNERC_TYPE8]

DOCFLOW_TO_GNERC_MAP = { GNERC_TYPE4 => 4, GNERC_TYPE5 => 5, GNERC_TYPE6 => 6, GNERC_TYPE8 => 8 }

JUSTICE_USER = 33
JUSTICE_USERNAME = 'justice'
JUSTICE_PASSWORD = 'justice'
JUSTICE_RESPONSE_URL = 'http://localhost:3000/applicant/response'

CANCEL_EXCEPTION_DOCTYPES = [ 3, 4, 12 ] # ბრძანება, განკარგულება, ხელშეკრულება

TEMPLATE_USER_ID = 34

FAYE_TOKEN = 'secret'
FAYE_SERVER = "http://1.1.2.65:9292/faye"
