GRANT SELECT ON DOCFLOW_DEV.HR_ORGANIZATIONS TO TEMOCH;
GRANT UPDATE ON DOCFLOW_DEV.HR_ORGANIZATIONS TO TEMOCH;
GRANT INSERT ON DOCFLOW_DEV.HR_ORGANIZATIONS TO TEMOCH;

GRANT SELECT ON DOCFLOW_DEV.HR_EMPLOYEES TO TEMOCH;
GRANT UPDATE ON DOCFLOW_DEV.HR_EMPLOYEES TO TEMOCH;
GRANT INSERT ON DOCFLOW_DEV.HR_EMPLOYEES TO TEMOCH;
