class SapHrSync < ActiveRecord::Migration
  def up
  	execute <<-SQL
      CREATE TABLE SAP_ORGANIZATIONS(
	    OBJECTID    NUMBER(8,0) NOT NULL,
	    OBJECTTYPE  VARCHAR2(1) NOT NULL,
	    BEGIN_DATE   DATE NOT NULL,
	    END_DATE     DATE NOT NULL,
	    LANGUAGE     VARCHAR2(2) NOT NULL,
	    SHORT_NAME   VARCHAR2(200),
	    CONSTRAINT organizations_primary_key PRIMARY KEY (OBJECTID, OBJECTTYPE, BEGIN_DATE, END_DATE, LANGUAGE)
	  )
    SQL

 	execute <<-SQL
	  CREATE TABLE SAP_ORGANIZATION_TEXTS(
		  OBJECTID    NUMBER(8,0) NOT NULL,
		  OBJECTTYPE  VARCHAR2(1) NOT NULL,
		  BEGIN_DATE   DATE NOT NULL,
		  END_DATE     DATE NOT NULL,
		  LANGUAGE     VARCHAR2(2) NOT NULL,
		  NAME         VARCHAR2(500),
		  CONSTRAINT org_texts_primary_key PRIMARY KEY (OBJECTID, OBJECTTYPE, BEGIN_DATE, END_DATE, LANGUAGE)
		)
    SQL

    execute <<-SQL
	  CREATE TABLE SAP_RELATIONS(
		  OBJECTID    NUMBER(8,0) NOT NULL,
		  OBJECTTYPE  VARCHAR2(1) NOT NULL,
		  BEGIN_DATE   DATE NOT NULL,
		  END_DATE     DATE NOT NULL,
		  RELATION     VARCHAR2(4) NOT NULL,
		  VARYF        VARCHAR2(10),
		  PRIORITY     VARCHAR2(2),
		  REL_OBJ_ID   NUMBER(8,0) NOT NULL,
		  REL_OBJ_TYPE VARCHAR2(1) NOT NULL,
		  CONSTRAINT relations_primary_key PRIMARY KEY (OBJECTID, OBJECTTYPE, BEGIN_DATE, END_DATE, RELATION, VARYF)
		)
    SQL

    execute <<-SQL
	  CREATE TABLE SAP_PERSONS(
		  PERSON_ID  NUMBER(8,0) NOT NULL,
		  BEGIN_DATE DATE NOT NULL,
		  END_DATE   DATE NOT NULL,
		  STATUS     NUMBER(1,0),
		  CONSTRAINT persons_primary_key PRIMARY KEY (PERSON_ID, BEGIN_DATE, END_DATE)
		)
    SQL


    execute <<-SQL
	  CREATE TABLE SAP_PERSON_ORG(
		  PERSON_ID      NUMBER(8,0) NOT NULL,
		  BEGIN_DATE     DATE NOT NULL,
		  END_DATE       DATE NOT NULL,
		  ORGANIZATION   NUMBER(8,0),
		  SHTAT          NUMBER(8,0),
		  CONSTRAINT person_org_primary_key PRIMARY KEY (PERSON_ID, BEGIN_DATE, END_DATE)
		)
    SQL

    execute <<-SQL
	  CREATE TABLE SAP_PERSON_NAME(
		  PERSON_ID      NUMBER(8,0) NOT NULL,
		  BEGIN_DATE     DATE NOT NULL,
		  END_DATE       DATE NOT NULL,
		  LANGUAGE       VARCHAR2(2) NOT NULL,
		  FIRSTNAME      VARCHAR2(100),
		  LASTNAME       VARCHAR2(100),
		  MIDDLENAME     VARCHAR2(100),
		  GENDER         VARCHAR2(1),
		  CONSTRAINT person_name_primary_key PRIMARY KEY (PERSON_ID, BEGIN_DATE, END_DATE, LANGUAGE)
		)
    SQL
  end

  def down
  	execute "drop table SAP_PERSON_NAME"
  	execute "drop table SAP_PERSON_ORG"
  	execute "drop table SAP_PERSONS"
  	execute "drop table SAP_RELATIONS"
  	execute "drop table SAP_ORGANIZATION_TEXTS"
    execute "drop table SAP_ORGANIZATIONS"
  end
end
